version: '3.9'

services:
  app:
    container_name: backend
    build:
      context: .
      dockerfile: docker/Backend.Dockerfile
    restart: always
    command: >
      sh -c "python manage.py wait_for_db &&
             python manage.py makemigrations &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    ports:
      - 8000:8000
    volumes:
      - ./app:/app
      - ./data/web:/vol/web
    environment:
      - SECRET_KEY=devsecretkey
      - DEBUG=1
      - DB_HOST=db
      - DB_NAME=devdb
      - DB_USER=devuser
      - DB_PASS=changeme
    depends_on:
      - db
      - redis

  db:
    container_name: postgresql_db
    image: postgres:13-alpine
    restart: always
    volumes:
      - ./data/db:/var/lib/postgresql/data
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=devdb
      - POSTGRES_USER=devuser
      - POSTGRES_PASSWORD=changeme
    ports:
      - 5432:5432

  pgadmin:
    container_name: pgadmin4
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: devuser@devuser.com
      PGADMIN_DEFAULT_PASSWORD: changeme
      PGADMIN_LISTEN_PORT: 5050
    ports:
      - 5050:5050
    depends_on:
      - db

  celery:
    container_name: celery
    image: celery
    build:
      context: .
      dockerfile: docker/Backend.Dockerfile
    restart: always
    command: celery -A app worker -l info
    volumes:
      - ./app:/app
    environment:
      - SECRET_KEY=devsecretkey
      - DEBUG=1
    depends_on:
      - db
      - redis
      - app

  redis:
    container_name: redis
    image: redis
    restart: always
    ports:
      - 6379:6379

  vueapp:
    container_name: frontend
    image: vuejs/ci
    build:
      context: .
      dockerfile: docker/Frontend.Dockerfile
      args:
        - VUE_APP_API_URL=${VUE_APP_API_URL}
        - VUE_APP_GRAPHQL_URL=${VUE_APP_GRAPHQL_URL}
    restart: always
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - 8080:80
    environment:
      - CHOKIDAR_USEPOLLING=true
      - VUE_APP_API_URL=http://localhost:8000
      - VUE_APP_GRAPHQL_URL=http://localhost:8000/graphql

    depends_on:
      - app

volumes:
  postgres_data: