[tool.poetry]
name = "groove-ory-cloud"
version = "0.1.0"
description = "Groove Shop Ory Cloud as an Authentication backend"
authors = ["vtotskas <vassilistotskas@msn.com>"]

[tool.poetry.dependencies]
python = "^3.9"
Django = "^4.1"
django-environ = "^0.9.0"
django-ory-auth = "^0.1.3"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
