export enum MainRouteNames {
	HOME = 'Home',
	LOGIN = 'LogIn',
	SIGNUP = 'SignUp',
	VERIFY_EMAIL = 'VerifyEmail',
	VERIFY_EMAIL_RESEND_INPUT = 'VerifyEmailResendInput',
	PASSWORD_RESET = 'PasswordReset',
	PASSWORD_RESET_CONFIRM = 'PasswordResetConfirm',
	USER_ACCOUNT = 'UserAccount',
	ORDERS = 'Orders',
	SETTINGS = 'Settings',
	FAVOURITES = 'Favourites',
	REVIEWS = 'Reviews',
	PASSWORD = 'Password',
	SEARCH = 'Search',
	CART = 'Cart',
	SUCCESS = 'Success',
	CHECKOUT = 'Checkout',
	ALL_PRODUCTS = 'AllProducts',
	PRODUCT = 'Product',
	CATEGORY = 'Category',
	BLOG = 'Blog',
	AUTHOR = 'Author',
	POST = 'Post',
	POSTS_BY_TAG = 'PostsByTag',
	PAGE_NOT_FOUND = 'PageNotFound',
	NOT_FOUND = 'NotFound',
}