# Generated by Django 3.2.11 on 2022-02-02 20:11

from django.db import migrations, models
import django.db.models.deletion
import product.models
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('description', tinymce.models.HTMLField(blank=True, null=True)),
                ('menu_image_one', models.ImageField(blank=True, null=True, upload_to='uploads/categories/')),
                ('menu_image_two', models.ImageField(blank=True, null=True, upload_to='uploads/categories/')),
                ('menu_main_banner', models.ImageField(blank=True, null=True, upload_to='uploads/categories/')),
                ('tags', models.CharField(blank=True, help_text='SEO keywords', max_length=100, null=True)),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='Favourite',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('product_code', models.CharField(default=product.models.generate_unique_code, max_length=100, unique=True)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('description', tinymce.models.HTMLField(blank=True, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=11, null=True)),
                ('active', models.CharField(choices=[('True', 'Active'), ('False', 'Not Active')], default=True, max_length=10)),
                ('stock', models.IntegerField(default=1)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('discount_percent', models.DecimalField(decimal_places=2, default=0.0, max_digits=11)),
                ('hits', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ('-date_added',),
            },
        ),
        migrations.CreateModel(
            name='ProductImages',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=50)),
                ('image', models.ImageField(blank=True, null=True, upload_to='uploads/products/')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='uploads/products/thumbnails/')),
                ('is_main', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Product Images',
            },
        ),
        migrations.CreateModel(
            name='Vat',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('value', models.DecimalField(decimal_places=1, max_digits=11)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('comment', models.CharField(blank=True, max_length=250)),
                ('rate', models.PositiveSmallIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)])),
                ('status', models.CharField(choices=[('New', 'New'), ('True', 'True'), ('False', 'False')], default='True', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product')),
            ],
            options={
                'verbose_name_plural': 'Reviews',
                'ordering': ['-updated_at'],
            },
        ),
    ]
