# Generated by Django 3.1.7 on 2021-11-27 11:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('url', models.CharField(blank=True, max_length=255, null=True)),
                ('title', models.CharField(blank=True, max_length=40, null=True)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='uploads/sliders/')),
            ],
            options={
                'verbose_name_plural': 'Sliders',
            },
        ),
        migrations.CreateModel(
            name='Slide',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(blank=True, max_length=255, null=True)),
                ('title', models.CharField(blank=True, max_length=40, null=True)),
                ('subtitle', models.CharField(blank=True, max_length=40, null=True)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('discount', models.DecimalField(decimal_places=2, default=0.0, max_digits=11)),
                ('button_label', models.CharField(blank=True, max_length=10, null=True)),
                ('show_button', models.BooleanField(default=True)),
                ('date_start', models.DateTimeField(auto_now_add=True)),
                ('date_end', models.DateTimeField()),
                ('order_position', models.IntegerField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='uploads/slides/')),
                ('slider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='slider.slider')),
            ],
            options={
                'verbose_name_plural': 'Slides',
                'ordering': ('-order_position',),
            },
        ),
    ]
