# Generated by Django 3.1.7 on 2021-11-27 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slider', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='slide',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/slides/thumbnails/'),
        ),
        migrations.AddField(
            model_name='slider',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/sliders/thumbnails/'),
        ),
        migrations.AlterField(
            model_name='slide',
            name='date_start',
            field=models.DateTimeField(),
        ),
    ]
