# Generated by Django 3.1.7 on 2021-11-27 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slider', '0002_auto_20211127_1353'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='slide',
            options={'ordering': ('order_position',), 'verbose_name_plural': 'Slides'},
        ),
        migrations.AddField(
            model_name='slider',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='uploads/sliders/videos/'),
        ),
    ]
