# Generated by Django 3.2.9 on 2021-12-04 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slider', '0003_auto_20211127_2002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slide',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='slider',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
