# Generated by Django 3.2.12 on 2022-02-27 14:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('zipcode', models.CharField(max_length=100)),
                ('place', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('paid_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('stripe_token', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PayWay',
            fields=[
                ('name', models.CharField(choices=[('Credit Card', 'Credit Card'), ('Pay On Delivery', 'Pay On Delivery'), ('Pay On Store', 'Pay On Store'), ('PayPal', 'PayPal')], max_length=50, primary_key=True, serialize=False, unique=True)),
                ('active', models.CharField(choices=[('True', 'Active'), ('False', 'Not Active')], default=True, max_length=15)),
                ('cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=11)),
                ('free_for_order_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=11)),
            ],
            options={
                'verbose_name_plural': 'Pay Ways',
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('quantity', models.IntegerField(default=1)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='order.order')),
            ],
        ),
    ]
